version: '3.3'
volumes:
  prometheus_data: {}
  grafana_data: {}
services:
  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    expose:
      - 9090
  grafana:
    image: grafana/grafana:7.5.5
    ports:
      - 3000:3000
    user: "104"
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    expose:
      - 3000
  grizzly:
    image: grafana/grizzly:0.2.0
    volumes:
      - "./grafana:/src/"
    depends_on:
      - grafana
    environment:
      - GRAFANA_URL=http://admin:admin@grafana:3000
    working_dir: /src/dashboards
    entrypoint: sh -c "../wait-for.sh grafana:3000 -- grr apply ./datasource.yaml && grr apply ./main.jsonnet && grr watch jsonnet/ ./main.jsonnet"
  node-app:
    build:
      context: node-app
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
    volumes:
      - ./node-app:/code
    command: npm run dev
    expose:
      - 8080
