groups:
  - name: DemoAlerts
    rules:
      - alert: InstanceDown
        expr: up{job="services"} < 1
        for: 1m
        labels:
          severity: low
        annotations:
          summary: "Alert with low severity."

      - alert: SomeNewAlerttt13
        expr: sum(checkouts_total) > 13
        labels:
          severity: info
          team: imt
          squad: ":poop:"
        annotations:
          summary: Some API error rate is elevated sebtest
          message: >-
            messagemessagemessage Overall failure rate for the Some API due to Lean errors has
            increased to {{ $value }} for the last 5
            minutes info
          runbook_url: "https://runbook_url.com"

      - alert: ANewAlert33
        expr: sum(checkouts_total) > 33
        labels:
          severity: info
          team: imt
          squad: dai
        annotations:
          summary: Data API error rate is elevated sebtest
          description: >-
            Overall failure rate for the Data API due to Lean errors has
            increased to {{ $value }} for the last 5
            minutes sebtest
          runbook_url: "https://runbook_url.com"

      - alert: InstanceDownCritical
        expr: up{job="services"} < 1
        for: 1m
        labels:
          severity: high
        annotations:
          summary: "Alert with high severity."
