groups:
  - name: DemoAlerts
    rules:
      - alert: InstanceDown
        expr: up{job="services"} < 1
        for: 1m
        labels:
          severity: low
        annotations:
          summary: "Alert with low severity."

      - alert: PaymentApiErrorRate210
        expr: sum(checkouts_total) > 210
        labels:
          severity: info
          team: imt
        annotations:
          summary: Data API error rate is elevated sebtest
          description: >-
            Overall failure rate for the Data API due to Lean errors has
            increased to {{ $value | humanizePercentage }} for the last 5
            minutes sebtest
          runbook_url: ""

      - alert: InstanceDownCritical
        expr: up{job="services"} < 1
        for: 1m
        labels:
          severity: high
        annotations:
          summary: "Alert with high severity."
