global:
  scrape_interval: 10s

scrape_configs:
- job_name: "node-app"
  static_configs:
  - targets: ["node-app:8080"]

rule_files:
- alert.yml

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: ['alertmanager:9093']
